<?php
//Import PHPMailer classes into the global namespace //These must be at the top of your script, not inside a function use PHPMailer\PHPMailer\PHPMailer; use PHPMailer\PHPMailer\Exception;
require 'PHPMailer/src/Exception.php'; require 'PHPMailer/src/PHPMailer.php'; require 'PHPMailer/src/SMTP.php'; //Load Composer's autoloader // require 'vendor/autoload.php'; $first_name= $_POST['first_name']; $surname= $_POST['surname']; $email_id= $_POST['email_id']; $location= $_POST['location']; $skill_set= $_POST['skill_set']; $Phone_numbers= $_POST['Phone_numbers']; $graduation= $_POST['graduation']; $g_graduation= $_POST['g_graduation']; $gender= $_POST['gender']; $year_of_experience= $_POST['year_of_experience']; $date_of_birth= $_POST['date_of_birth']; $apply_for= $_POST['apply_for']; $sp="";

$target_dir = "resume/"; $target_file = $target_dir . basename($_FILES["resume"]["name"]??''); $newFileName = $target_dir .''.$email_id.''.'.'. pathinfo($_FILES["resume"]["name"] ,PATHINFO_EXTENSION); $uploadOk = 1; $imageFileType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION)); if ($uploadOk == 0) { $image_error= "Sorry, your file was not uploaded."; // if everything is ok, try to upload file } else { if (move_uploaded_file($_FILES["resume"]["tmp_name"],$newFileName)) { } else { $image_error="Sorry, there was an error uploading your file."; } } 
$path = $newFileName;
//Create an instance; passing true enables exceptions $mail = new PHPMailer(true);
try { //Server settings $mail->SMTPDebug =0; //Enable verbose debug output $mail->isSMTP(); //Send using SMTP $mail->Host = 'mail.xms.co.in'; //Set the SMTP server to send through $mail->SMTPAuth = true; //Enable SMTP authentication $mail->Username = 'smtp@xmedia.in'; //SMTP username $mail->Password = 'chennai01'; //SMTP password $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS; //Enable implicit TLS encryption $mail->Port = 465;
//TCP port to connect to; use 587 if you have set SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS //Recipients $mail->setFrom($email_id, $first_name.$surname); $mail->addAddress(', 'HR@media'); 
$mail->addAddress('');
$mail->addAddress(
'); //Add a recipient

//Content $mail->isHTML(true); //Set email format to HTML $mail->Subject = 'Application for '.$apply_for.$sp.' Job'; $mail->Body = 'Applicant Name :'.$first_name.'&nbsp;'.$surname.'<br>'.'Applicant Mobile Number :'.'&nbsp;'.$Phone_numbers.'<br>'.'Applicant E-mail :'.'&nbsp;'.$email_id.'<br>Applicant Date of Birth :'.'&nbsp;'.$date_of_birth.'<br>Applicant Gender :'.'&nbsp;'.$gender.'<br>Applicant Education :'.'&nbsp;'.$g_graduation.'<br>Applicant Passed out Year :'.'&nbsp;'.$graduation.'<br>Post Applied For :'.'&nbsp;'.$apply_for.'<br>Year Of Experience :'.'&nbsp;'.$year_of_experience.'<br>Applicant Current Location :'.'&nbsp;'.$location.'<br>Applicant Skill Set :'.'&nbsp;'.$skill_set; $mail->addAttachment($path); $mail->AltBody = 'Application for '.$apply_for.$sp.' Job'; $mail->send();
echo "<script> alert('Successfully Submitted '); window.location.href='https://scopex.in/recruitments/'; </script>"; } catch (Exception $e) { echo "<script> alert('submission failed '); window.location.href='https://scopex.in/recruitments/'; </script>"; }
  echo "<script> alert('Successfully Submitted '); window.location.href='https://scopex.in/recruitments/'; </script>"; } catch (Exception $e) { echo "<script> alert('submission failed '); window.location.href='https://scopex.in/recruitments/'; </script>"; }
